image:
  repository: quay.io/rh-ee-bcordeir/movies-quarkus
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

probes:
  liveness:
    path: /q/health/live
  readiness:
    path: /q/health/ready

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

route:
  enabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
